version: '2'

networks:
  basic:

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.5.0
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
    ports:
      - "7050:7050"
    networks:
      - basic

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.5.0
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_CHAINCODE_EXTERNALBUILD=true
      - CORE_CHAINCODE_EXECUTABLE=com.founderz.chaincode.FounderzAgreementChainCode
      - CORE_CHAINCODE_JAVA_RUNTIME=java:21
    volumes:
      - /var/run/:/host/var/run/
      - ./src/main/java:/opt/gopath/src/github.com/chaincode
    ports:
      - "7051:7051"
      - "7052:7052"
    networks:
      - basic
    depends_on:
      - orderer.example.com